/// <reference types="expo/types" />

// NOTE: This file should not be edited. It is generated by Expo and pulls in the
// Metro environment typings (`process.env.EXPO_PUBLIC_*` as `string | undefined`,
// asset modules, `require.context`).
